# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CAS_Show.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtWebEngineWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(752, 608)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.Severity_ComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.Severity_ComboBox.setObjectName("Severity_ComboBox")
        self.Severity_ComboBox.addItem("")
        self.Severity_ComboBox.addItem("")
        self.Severity_ComboBox.addItem("")
        self.Severity_ComboBox.addItem("")
        self.Severity_ComboBox.addItem("")
        self.verticalLayout.addWidget(self.Severity_ComboBox)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.Light_ComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.Light_ComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Light_ComboBox.setObjectName("Light_ComboBox")
        self.Light_ComboBox.addItem("")
        self.Light_ComboBox.addItem("")
        self.Light_ComboBox.addItem("")
        self.Light_ComboBox.addItem("")
        self.Light_ComboBox.addItem("")
        self.Light_ComboBox.addItem("")
        self.verticalLayout.addWidget(self.Light_ComboBox)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.Weather_ComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.Weather_ComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Weather_ComboBox.setAutoFillBackground(False)
        self.Weather_ComboBox.setObjectName("Weather_ComboBox")
        self.Weather_ComboBox.addItem("")
        self.Weather_ComboBox.addItem("")
        self.Weather_ComboBox.addItem("")
        self.Weather_ComboBox.addItem("")
        self.Weather_ComboBox.addItem("")
        self.Weather_ComboBox.addItem("")
        self.Weather_ComboBox.addItem("")
        self.Weather_ComboBox.addItem("")
        self.verticalLayout.addWidget(self.Weather_ComboBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.ShowMap_Button = QtWidgets.QPushButton(self.centralwidget)
        self.ShowMap_Button.setObjectName("ShowMap_Button")
        self.verticalLayout_2.addWidget(self.ShowMap_Button)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.map_widget = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.map_widget.setObjectName("map_widget")
        self.horizontalLayout.addWidget(self.map_widget)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 8)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # connect the button to the function
        self.ShowMap_Button.clicked.connect(self.print_all_comboboxes)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Crash severity"))
        self.Severity_ComboBox.setItemText(0, _translate("MainWindow", "--Severity--"))
        self.Severity_ComboBox.setItemText(1, _translate("MainWindow", "Non-Injury Crash"))
        self.Severity_ComboBox.setItemText(2, _translate("MainWindow", "Minor Crash"))
        self.Severity_ComboBox.setItemText(3, _translate("MainWindow", "Serious Crash"))
        self.Severity_ComboBox.setItemText(4, _translate("MainWindow", "Fatal Crash"))
        self.label_2.setText(_translate("MainWindow", "Light"))
        self.Light_ComboBox.setItemText(0, _translate("MainWindow", "--Light--"))
        self.Light_ComboBox.setItemText(1, _translate("MainWindow", "Bright sun"))
        self.Light_ComboBox.setItemText(2, _translate("MainWindow", "Overcast"))
        self.Light_ComboBox.setItemText(3, _translate("MainWindow", "Dark"))
        self.Light_ComboBox.setItemText(4, _translate("MainWindow", "Twilight"))
        self.Light_ComboBox.setItemText(5, _translate("MainWindow", "Unknown"))
        self.label_3.setText(_translate("MainWindow", "Weather"))
        self.Weather_ComboBox.setItemText(0, _translate("MainWindow", "--Weather--"))
        self.Weather_ComboBox.setItemText(1, _translate("MainWindow", "Fine"))
        self.Weather_ComboBox.setItemText(2, _translate("MainWindow", "Light rain"))
        self.Weather_ComboBox.setItemText(3, _translate("MainWindow", "Heavy rain"))
        self.Weather_ComboBox.setItemText(4, _translate("MainWindow", "Null"))
        self.Weather_ComboBox.setItemText(5, _translate("MainWindow", "Mist or Fog"))
        self.Weather_ComboBox.setItemText(6, _translate("MainWindow", "Snow"))
        self.Weather_ComboBox.setItemText(7, _translate("MainWindow", "Hail or Sleet"))
        self.ShowMap_Button.setText(_translate("MainWindow", "Show Data"))





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
